# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 579c0764ce728f7e2dbea380cc82510bd070de3ed28d3d0f280b0bf2ffb573a68cdb03690bb0480526f3739af4053e2776fc09a08383f695eef354b0fe6fa02d

test:
  secret_key_base: 81aaa54c96165b14e92b82ca149244f77d50a7ecd4d53a3209227c0c9f11fc52a988a3ea1fcb92e48da84523f31481bfe54799dc7cc5f09dc0fcdc12124ed27c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
